[tool.poetry]
name = "asystent"
version = "0.1.0"
description = ""
authors = ["Michał Dzieza"]
readme = "README.md"
packages = [{include = "asystent"}]

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
